### ISSUE TITLE
Create button on triplets experiment page to download embedding

### ISSUE THREAD

**Issue by lalitkumarj** [kgjamieson/NEXT-psych#22]
Upon clicking, the user should get a csv file with a column corresponding to the primary_description of the target and then multiple columns corresponding to the embedding.

**Comment by stsievert** [comment]
This was closed with 76497801603e1ccacb668d0f0863968a7b52a70b and the embedding download is only available for the triplet algorithm as in eeadc59a398c6a5a7035e140867987540bf72741 (via a Jekyll if statement -- eek!)
