### ISSUE TITLE
Random Sampling does not work from Dueling Bandits launch experiment interface

### ISSUE THREAD

**Issue by flownandez** [kgjamieson/NEXT-psych#4]
Experiment design interface says "oops there is an error" if we try to use the "random sampling" algorithm instead of the default algorithm (Dueling Bandits).

**Comment by stsievert** [comment]
This is present when adding the uncertainty sampling too. I believe it's an issue with adding an algorithm.

**Comment by stsievert** [comment]
Closed. Added options for the algorithms in [Info.py](https://github.com/kgjamieson/NEXT-psych/blob/master/next/apps/DuelingBanditsPureExploration/Info.py#L61) in the new_experiment_params.html lists the supported algorithms in DuelingBanditsPureExploration.

It looks like Random Sampling and Uncertainty Sampling are not implemented for Dueling Bandits. I removed those options, which doesn't feel kosher.

**Comment by lalitkumarj** [comment]
But does the edit functionality work? That's the key.

**Comment by stsievert** [comment]
No, it doesn't work. I had thought you had added the functionality to edit a while ago?

**Comment by lalitkumarj** [comment]
Just on triplets...go look at how it is done. IT's the same mechanism
across all of them.

**Comment by stsievert** [comment]
I can do that tomorrow... I'll have to dig into a bit. I edited some of the triplet code and right now for editing a triplet experiment, I get the below:
![screen shot 2015-10-28 at 8 33 00 pm](https://cloud.githubusercontent.com/assets/1320475/10807922/47b30d80-7db3-11e5-9468-a7798316369f.png)

**Comment by lalitkumarj** [comment]
No...something has clearly broken. I got this working.

**Comment by stsievert** [comment]
I added the ability to edit DuelingBandits algorithms.

I also added a clarification when editing an experiment... if it's running, you can only edit the name/description.

![screen shot 2015-10-29 at 10 11 39 am](https://cloud.githubusercontent.com/assets/1320475/10822523/a451c37a-7e25-11e5-8b7f-d9a169fd03e9.png)
