### ISSUE TITLE
"server error" if you try to download the data paricipant response data (Dueling Bandits)

### ISSUE THREAD

**Issue by flownandez** [kgjamieson/NEXT-psych#6]
"server error" if you try to download the data paricipant response data (Dueling Bandits)

**Comment by lalitkumarj** [comment]
Thanks for fixing this Scott.

**Comment by stsievert** [comment]
I thought this issue was still present only for the dueling bandits. I fixed the CSV extension (from .html to .csv) I thought that this issue was still present.
